```{r}
library(dplyr)
library(stringr)
library(janitor)

knitr::opts_knit$set(root.dir = "/global/scratch/users/minoli/maps")
```

```{r}
map_df <- read_csv("../results/summary/all_species_map.csv", show_col_types = FALSE)
vgp_freeze_df <- read_csv("../data/vgp_phase1_freeze.csv", show_col_types = FALSE)

contact_list <- map_df %>%
  filter(
    priority %in% c(1, 2, 3, 5),
    !domesticated_flag,
    !grepl("^Homo sapiens$", scientific_name, ignore.case = TRUE)
  ) %>%
  mutate(
    contact_priority = case_when(
      priority %in% c(1, 2) ~ "1",
      priority %in% c(3, 5) ~ "2",
      TRUE ~ NA_character_
    ),
    contact_reason = case_when(
      priority == 1 ~ "Missing sampling location",
      priority == 2 ~ "Missing sampling location",
      priority == 3 ~ "Vague location + outside/missing range",
      priority == 5 ~ "Vague location inside range",
      TRUE ~ NA_character_
    )
  ) %>%
  arrange(factor(contact_priority, levels = c("1","2")),
          priority, scientific_name)
```

```{r}
vgp_contacts <- vgp_freeze_df %>%
  janitor::clean_names() %>%
  dplyr::select(
    accession_number_for_main_haplotype,
    primary_contact,
    other_contacts)

submitters_to_contact <- contact_list %>%
  left_join(vgp_contacts, by = "accession_number_for_main_haplotype") %>%
  dplyr::select(
    scientific_name, english_name,
    biosample_accession, accession_number_for_main_haplotype,
    contact_priority, contact_reason,
    geo_location, sampling_lon, sampling_lat, map_notes,
    biosample_provider, biosample_collectedby,
    primary_contact, other_contacts
  )

exclude_species <- c("Cottoperca gobio")

submitters_to_contact_final <- submitters_to_contact %>%
  filter(!scientific_name %in% exclude_species)

submitters_to_contact_final
# write.csv(submitters_to_contact_final, "../results/summary/submitters_to_contact.csv", row.names = FALSE)

```

